### PR TITLE
partial translation p03_ch01_the_value_of_universally_preferable_beha…

### PR DESCRIPTION
**Pull request by bluishjane**
…viour

### CODE REVIEW

**Comment by plokmi** [comment]
The structure of the commit seems wrong, @TheOutspokenKing could you recheck?

**Comment by TheOutspokenKing** [comment]
Sure, let me recheck it again now. And what error are you noticing? @plokmi

**Comment by plokmi** [comment]
Well this, 

The translator didn't remove the original texts after translation.

**Comment by TheOutspokenKing** [comment]
I see but in the translations being accepted on github, both the English words and the translated language words goes side by side in a proper paragraph. So what original texts are you talking about?

**Comment by plokmi** [comment]
Afaik, the English sentences should be completed translated into the translated language. Which in this commit, the translator forgot to remove the original English text, which in a way, the same context is being stated twice as shown above.

**Pull request merged**
